meta:
  epub_title: Holy Bible
  version_number: '0.5'
  publication_date: May 2025
  bible_edition: Tell The Truth
  creator: "God"
  publisher: "Zondervan"
  rights: "© 2025 Arto Kalishian"
  subject: "Bible; Christianity; Scripture; Holy"
  output_markdown: true

fonts:
  font_path: serif
  spoken_font_path: serif

formatting:
  epub_title_font_size: 3em
  book_title_font_size: 3.6em
  chapter_title_font_size: 2em
  verse_font_size: 1em
  superscript_font_size: 0.8em
  line_spacing: 1.3
  convert_smart_quotes: true
  god_word_capital_font_size: 0.8em
  bold_superscript_verse_numbers: true
  edition_info_font_size: 0.8em

footnotes:
  footnote_font_size: 0.7em
  footnotes_title: Translation Notes
  footnotes_title_font_size: 1.3em
  footnote_letter_bold: false

output:
  generate_markdown: true
  markdown_superscript_style: bold
  markdown_output_verse_by_verse: true
  include_toc_page: true

json_structure:
  sections:
    - headline (string)
    - verses:
        - verse_number (int)
        - text (string)
  footnotes:
    - verse (int)
    - letter (optional string)
    - content (string)
